# Generated by Django 2.0.7 on 2018-07-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('context', models.TextField(max_length=6000)),
                ('inDate', models.DateField(verbose_name='등록 날짜')),
            ],
        ),
    ]
